apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-api
  labels:
    name: my-api
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: my-api
    spec:
      containers:
        - image: ost0318/api:alpine
          name: my-api
          resources:
            limits:
              cpu: "1"
              memory: "1G"
            requests:
              cpu: "20m"
              memory: "55M"
          # livenessProbe:
          #   httpGet:
          #     path: /_status/healthz
          #     port: 5000
          #   initialDelaySeconds: 90
          #   timeoutSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /_status/healthz
          #     port: 5000
          #   initialDelaySeconds: 30
          #   timeoutSeconds: 10
          # env:
          #   - name: ENVVARNAME
          #     value: ENVVARVALUE
          ports:
            - containerPort: 80
              name: my-api
            - containerPort: 443
              name: my-api
          # volumeMounts:
          #   - mountPath: /data
          #     name: data
      # volumes:
      #   - name: data
      #     emptyDir: {}
      restartPolicy: Always
      imagePullPolicy: Always
