apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server-dep
    tier: server
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - image: ost0318/api
          name: server
          resources:
            requests:
              cpu: "20m"
              memory: "55M"
            limits:
              cpu: "1"
              memory: "1G"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /v1/ping
              port: 8080
          readinessProbe:
            httpGet:
              path: /v1/ping
              port: 8080
